import { ContentPackStore } from '@/features/compendium/store'
import { GetItem, GetValue, SetValue } from './Storage'
import { parseContentPack } from './ContentPackParser'
import logger from '@/user/logger'
import type { IContentPack } from '@/classes/ContentPack'

/**
 * Every official Massif Press content pack is bundled with the application
 * (`public/lcps`, generated by `scripts/fetch-official-lcps.mjs` from the open
 * massif-press data repositories) and installed - and activated - on first run,
 * so the compendium resolves official content such as the Caliban's integrated
 * HHS-075 "Flayer" Shotgun without the player having to install anything.
 *
 * Packs are persisted exactly like a manually installed `.lcp`, so they show up
 * in the content manager and can be deactivated or removed there. Removing one
 * is remembered: it is never reinstalled behind the player's back.
 */
export interface OfficialPackInfo {
  file: string
  id: string
  name: string
  author: string
  version: string
  itemPrefix?: string
  v3?: boolean
  collections?: string[]
  repo?: string
}

const INDEX_DIR = 'lcps'
const INDEX_FILE = 'index.json'
/** Ids of the bundled packs already offered to this installation. */
const OFFERED_KEY = 'official_packs_installed'

export function officialPackIndexURL(): string {
  return `${import.meta.env.BASE_URL}${INDEX_DIR}/${INDEX_FILE}`
}

export function officialPackURL(file: string): string {
  return `${import.meta.env.BASE_URL}${INDEX_DIR}/${file}`
}

export async function fetchOfficialPackIndex(): Promise<OfficialPackInfo[]> {
  const response = await fetch(officialPackIndexURL(), { cache: 'no-cache' })
  if (!response.ok) throw new Error(`HTTP ${response.status} fetching ${INDEX_FILE}`)
  const index = await response.json()
  if (!Array.isArray(index)) throw new Error(`${INDEX_FILE} is not a pack list`)
  return index.filter(entry => entry && typeof entry.file === 'string' && typeof entry.id === 'string')
}

export async function downloadOfficialPack(entry: OfficialPackInfo): Promise<IContentPack> {
  const response = await fetch(officialPackURL(entry.file), { cache: 'no-cache' })
  if (!response.ok) throw new Error(`HTTP ${response.status} fetching ${entry.file}`)
  const pack = await parseContentPack(await response.arrayBuffer())
  pack.active = true
  return pack
}

/**
 * Installs any bundled official pack this installation has not seen yet.
 * Returns the number of packs installed. Never throws: offline players and
 * broken downloads must not stop the application from starting.
 */
export async function installOfficialContentPacks(): Promise<number> {
  let index: OfficialPackInfo[]
  try {
    index = await fetchOfficialPackIndex()
  } catch (error) {
    logger.warn(`Official content packs unavailable: ${error}`)
    return 0
  }

  const store = ContentPackStore()
  const offered = new Set<string>((await GetValue(OFFERED_KEY)) || [])
  const pending = index.filter(
    entry =>
      !offered.has(entry.id) && !store.ContentPacks.some(pack => pack.ID === entry.id)
  )
  if (!pending.length) return 0

  const packs: IContentPack[] = []
  for (const entry of pending) {
    try {
      if (await GetItem('content', entry.id)) {
        // installed by an earlier session, before this bookkeeping existed
        offered.add(entry.id)
        continue
      }
      packs.push(await downloadOfficialPack(entry))
      offered.add(entry.id)
    } catch (error) {
      logger.error(`Failed to install official content pack ${entry.name}: ${error}`)
    }
  }

  await SetValue(OFFERED_KEY, [...offered])
  if (!packs.length) return 0

  await store.installContentPacks(packs)
  logger.info(
    `Installed ${packs.length} official content pack(s): ` +
      packs.map(pack => pack.manifest.name).join(', ')
  )
  return packs.length
}
